import { BiMaleSign, BiFemaleSign } from "react-icons/bi";

export const AnimaisAdoteJa = [
  {
    id: 1,
    imagem: [
      "/images/pacoca1.jpeg",
      "/images/pacoca2.jpeg",
      "/images/pacoca3.jpeg",
      "/images/pacoca4.jpeg",
    ],
    nome: "Paçoca",
    tempo: "5 anos",
    local: "Ouro Preto/MG",
    tamanho: "P",
    sexo: "Femêa",
    descricao:
      "Adora passear todos os dias, ama andar de carro e tirar um cochilo depois do almoço. De manhã e de noite, é um anjo, mas de dia é uma fera. Come muito e morre de medo de tomar banho..",
    Raca: "Shih Tzu",
    icone: <BiFemaleSign />,
  },
  {
    id: 2,
    imagem: [
      "/images/benji1.jpeg",
      "/images/benji2.jpeg",
      "/images/benji3.jpeg",
      "/images/benji4.jpeg",
    ],
    nome: "Benji",
    tempo: "5 anos",
    local: "Belo Horizonte/MG",
    tamanho: "M",
    sexo: "Macho",
    descricao:
      "Ele era de um parente da minha família, porém essa pessoa estava passando por problemas difíceis uma época e chegou até a tomar remédios controlados, e nesse momento o Benji acabou sendo maltratado. Quando pegamos ele, estava um pouco traumatizado, mas com o tempo aqui em casa, dando carinho para ele, melhorou bastante. ",
    Raca: "Vira-lata",
    icone: <BiMaleSign />,
  },
  {
    id: 3,
    imagem: [
      "/images/suzi1.jpeg",
      "/images/suzi2.jpeg",
      "/images/suzi3.jpeg",
      "/images/suzi4.jpeg",
    ],
    nome: "Suzi",
    tempo: "2 anos",
    local: "Barra Longa/MG",
    tamanho: "P",
    sexo: "Fêmea",
    descricao:
      "Suzi é a cadelinha mais brincalhona que eu já tive, ela adora fazer bagunça e brincar, seja com adultos ou crianças. Uma cadela amável que adora brincar com a bolinha dela e de morder (suavemente) as pessoas pedindo atenção. Nas horas vagas ela dorme, na verdade ela hiberna em sua caminha.Entretanto quando ela está elétrica não pode ver um portão que já quer ir pra rua correr.",
    Raca: "Shih-tzu",
    icone: <BiFemaleSign />,
  },

  {
    id: 4,
    imagem: [
      "/images/lancelot1.jpeg",
      "/images/lancelot2.jpeg",
      "/images/lancelot3.jpeg",
      "/images/lancelot4.jpeg",
    ],
    nome: "Lancelot",
    tempo: "6 anos",
    local: "Belo Horizonte/MG",
    tamanho: "M",
    sexo: "Macho",
    descricao:
      "Hobbys: entrar dentro de espaços apertados, dormir muito e brincar de pega pega.",
    Raca: "",
    icone: <BiMaleSign />,
  },
  {
    id: 5,
    imagem: [
      "/images/amora1.jpeg",
      "/images/amora2.jpeg",
      "/images/amora3.jpeg",
      "/images/amora4.jpeg",
    ],
    nome: "Amora",
    tempo: "3 anos",
    local: "Belo Horizonte/MG",
    tamanho: "M",
    sexo: "Fêmea",
    descricao:
      "Ela é muito agitada, ansiosa e gosta de latir pra galera pra tá passando na rua. Mesmo assim, ela faz muita amizade com os vizinhos daqui, a rua toda conhece e gosta dela e os carteiros também.",
    Raca: "Vira-lata",
    icone: <BiFemaleSign />,
  },
  {
    id: 6,
    imagem: [
      "/images/juca1.jpeg",
      "/images/juca2.jpeg",
      "/images/juca3.jpeg",
      "/images/juca4.jpeg",
    ],
    nome: "Juca",
    tempo: "3 anos",
    local: "Conselheiro Lafaiete/MG",
    tamanho: "M",
    sexo: "Macho",
    descricao:
      "Ele tem problema nas patas de trás, por isso, tem que usar cadeira de rodas. Ele é animado, gosta de carinho e companhia",
    Raca: "Vira-lata",
    icone: <BiMaleSign />,
  },
  {
    id: 7,
    imagem: [
      "/images/pantera1.jpeg",
      "/images/pantera2.jpeg",
      "/images/pantera3.jpeg",
      "/images/pantera4.jpeg",
    ],
    nome: "Pantera",
    tempo: "4 anos",
    local: "Conselheiro Lafaiete/MG",
    tamanho: "M",
    sexo: "Fêmea",
    descricao: "",
    Raca: "Vira-lata",
    icone: <BiFemaleSign />,
  },
  {
    id: 8,
    imagem: [
      "/images/juju1.jpeg",
      "/images/juju2.jpeg",
      "/images/juju3.jpeg",
      "/images/juju4.jpeg",
    ],
    nome: "Juju",
    tempo: "4 anos",
    local: "Conselheiro Lafaiete/MG",
    tamanho: "M",
    sexo: "Fêmea",
    descricao: "",
    Raca: "Vira-lata",
    icone: <BiFemaleSign />,
  },
  {
    id: 9,
    imagem: [
      "/images/thor2.jpeg",
      "/images/thor1.jpeg",
      "/images/thor3.jpeg",
      "/images/thor4.jpeg",
    ],
    nome: "Thor",
    tempo: "2 anos",
    local: "Conselheiro Lafaiete/MG",
    tamanho: "P",
    sexo: "Macho",
    descricao:
      "Ele é nem lerdo, tá sempre no ritmo dele e gosta de dormir no sofá quando alguém tá assistindo série.",
    Raca: "Vira-lata",
    icone: <BiMaleSign />,
  },
  {
    id: 10,
    imagem: [
      "/images/dumbo1.jpeg",
      "/images/dumbo2.jpeg",
      "/images/dumbo3.jpeg",
      "/images/dumbo4.jpeg",
    ],
    nome: "Dumbo",
    tempo: "3 anos",
    local: "Conselheiro Lafaiete/MG",
    tamanho: "P",
    sexo: "Macho",
    descricao:
      "Ele é bff da Luna, desde que se conheceram não se separaram mais. ele gosta de carinho e é ciumento, além disso tem umas patinhas curtas que todo mundo ama.",
    Raca: "Vira-lata",
    icone: <BiMaleSign />,
  },
  {
    id: 11,
    imagem: [
      "/images/zuko1.jpeg",
      "/images/zuko2.jpeg",
      "/images/zuko3.jpeg",
      "/images/zuko4.jpeg",
    ],
    nome: "Zuko",
    tempo: "3 anos",
    local: "Muriaé-MG",
    tamanho: "M",
    sexo: "Macho",
    descricao:
      "O Zuko é um cachorro q adora atenção e ficar perto das pessoas, ele é bem calmo até você deixar ele empolgado, a partir disso nem ele consegue se controlar mais. No geral ele é bem inteligente e obediente (um pouco medroso também) ou seja, a companhia perfeita.",
    Raca: "Pastor alemão",
    icone: <BiMaleSign />,
  },

  {
    id: 12,
    imagem: [
      "/images/amoraELilica1.jpeg",
      "/images/amoraELilica2.jpeg",
      "/images/amoraELilica3.jpeg",
      "/images/amoraELilica4.jpeg",
    ],
    nome: "Amora e Lilica",
    tempo: "8 anos e 1 mês",
    local: "Belo Horizonte/MG",
    tamanho: "G",
    sexo: "Fêmea",
    descricao: "Gêmias inseparáveis e muito bricalhonas.",
    Raca: "Rottweiler",
    icone: <BiFemaleSign />,
  },
  {
    id: 13,
    imagem: [
      "/images/mel1.jpeg",
      "/images/mel2.jpeg",
      "/images/mel3.jpeg",
      "/images/mel4.jpeg",
    ],
    nome: "Mel",
    tempo: "16 anos",
    local: "Belo Horizonte/MG",
    tamanho: "P",
    sexo: "Fêmea",
    descricao:
      "Melzinha é e sempre foi muito mau humorada e bravinha! Sempre latiu muito e isso não mudou depois de velhinha. Ama comer de tudo, principalmente pão de sal. Gosta dos seus irmãozinhos, mas é impaciente com eles, já que eles são crianças ainda.",
    Raca: "Poodle",
    icone: <BiFemaleSign />,
  },
  {
    id: 14,
    imagem: [
      "/images/edSheeran1.jpeg",
      "/images/edSheeran2.jpeg",
      "/images/edSheeran3.jpeg",
      "/images/edSheeran4.jpeg",
    ],
    nome: "Ed Sheeran",
    tempo: "3 anos",
    local: "São Paulo/SP",
    tamanho: "M",
    sexo: "Macho",
    descricao:
      "Ama sachê, odeia visitas, gosta de dormir sozinho em guarda roupas, é bem interesseiro e dramático e ruim (coitado dos passarinhos que caem no quintal).",
    Raca: "Vira-lata",
    icone: <BiMaleSign />,
  },
  {
    id: 15,
    imagem: [
      "/images/ayka1.jpeg",
      "/images/ayka2.jpeg",
      "/images/ayka3.jpeg",
      "/images/ayka4.jpeg",
    ],
    nome: "Ayka",
    tempo: "12 anos",
    local: "São Paulo/SP",
    tamanho: "P",
    sexo: "Fêmea",
    descricao:
      "Ela é bem estressada, como toda pinscher, ela come todo tipo de alimento, é bem ciumenta, ama uma coberta e ama passear.",
    Raca: "Pinscher",
    icone: <BiFemaleSign />,
  },
  {
    id: 16,
    imagem: [
      "/images/evie1.jpeg",
      "/images/evie2.jpeg",
      "/images/evie3.jpeg",
      "/images/evie4.jpeg",
    ],
    nome: "Evie",
    tempo: "4 anos",
    local: "São Paulo/SP",
    tamanho: "P",
    sexo: "Fêmea",
    descricao:
      "Ela é bem dócil com a família, um pouco estressada, uma verdadeira caçadora de animais pequenos, ama brincar, além de destruir e dormir nas plantas.",
    Raca: "Vira-lata",
    icone: <BiFemaleSign />,
  },
  {
    id: 17,
    imagem: [
      "/images/nina1.jpeg",
      "/images/nina2.jpeg",
      "/images/nina3.jpeg",
      "/images/nina4.jpeg",
    ],
    nome: "Nina",
    tempo: "4 anos",
    local: "Lagoa da Prata/MG",
    tamanho: "M",
    sexo: "Fêmea",
    descricao:
      "A cadela é uma Golden Retriever que ama brincar com um flamingo de brinquedo, também gosta de dormir muito e come bastante.",
    Raca: "Golden Retriever",
    icone: <BiFemaleSign />,
  },

  {
    id: 18,
    imagem: [
      "/images/teddy1.jpeg",
      "/images/teddy2.jpeg",
      "/images/teddy3.jpeg",
      "/images/teddy4.jpeg",
    ],
    nome: "Teddy",
    tempo: "6 anos",
    local: "Belo Horizonte/MG",
    tamanho: "P",
    sexo: "Macho",
    descricao:
      "Ele adora brincar e dormir na cama, mas odeia que tirem foto ou filmes ele, ele é adulto de porte pequeno.",
    Raca: "Vira-lata",
    icone: <BiMaleSign />,
  },

  {
    id: 19,
    imagem: [
      "/images/bob2.jpg",
      "/images/bob1.jpg",
      "/images/bob3.jpg",
      "/images/bob4.jpg",
    ],
    nome: "Bob",
    tempo: "3 anos",
    local: "Betim/MG",
    tamanho: "M",
    sexo: "Macho",
    descricao: "Um cachorro dócil e amigáve",
    Raca: "Vira-lata",
    icone: <BiMaleSign />,
  },

  {
    id: 20,
    imagem: [
      "/images/pepeu3.jpeg",
      "/images/pepeu1.jpeg",
      "/images/pepeu2.jpeg",
      "/images/pepeu4.jpeg",
    ],
    nome: "Pepeu",
    tempo: "8 anos",
    local: "Belo Horizonte/MG",
    tamanho: "M",
    sexo: "Macho",
    descricao:
      "Pepeu é um cachorro q apesar de ter VÁRIOS problemas de saúde(alergia até à terra), pepeu é muito aventureiro. Adora caçar, desde insetos até macacos. Ele é bem inquieto e companheiro, enquanto tiver gente acordada ele está junto. A coisa que ele mais gosta de fazer, dentro de casa é ficar na varanda olhando o movimento da rua.",
    Raca: "Poodle",
    icone: <BiMaleSign />,
  },
  {
    id: 21,
    imagem: [
      "/images/lola1.jpeg",
      "/images/lola2.jpeg",
      "/images/lola3.jpeg",
      "/images/lola4.jpeg",
    ],
    nome: "Lola",
    tempo: "3 anos",
    local: "Belo Horizonte/MG",
    tamanho: "M",
    sexo: "Fêmea",
    descricao:
      "A coisa que Lola mais ama fazer é dormir. Enquanto tiver alguém deitado, ela está junto. Se o quarto estiver escuro então, melhor ainda. Além disso Lola odeia que não durmam no horário certo, ela começa a ficar estressada e vai procurar outro quarto ou então embaixo da cama pra dormir.",
    Raca: "Poodle",
    icone: <BiFemaleSign />,
  },

  {
    id: 22,
    imagem: [
      "/images/frida2.jpeg",
      "/images/frida1.jpeg",
      "/images/frida3.jpeg",
      "/images/frida4.jpeg",
    ],
    nome: "Frida",
    tempo: "4 anos",
    local: "Três Pontas/MG",
    tamanho: "P",
    sexo: "Fêmea",
    descricao:
      "É a dona da casa. Ela é muito anti-social, não gostou nem um pouquinho dos filhotes qd eles chegaram, odeia ser pega no colo, odeia crianças, mas adora um carinho na cabeça e passa o dia inteiro na varanda ou dando role nos muros",
    Raca: "Vira-lata",
    icone: <BiFemaleSign />,
  },
];

export default AnimaisAdoteJa;
